'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'zh' | 'ko' | 'en'

interface LanguageContextType {
  language: Language
  currentLanguage: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// 다국어 번역 데이터
const translations = {
  zh: {
    // 헤더
    'nav.home': '小洪书',
    'nav.instagram': 'Instagram',
    'nav.experiences': '体验活动',
    'nav.reviews': '体验后记',
    'nav.about': '关于我们',
    'nav.admin': '管理员',
    'nav.login': '登录',
    'nav.register': '注册',
    'nav.mypage': '个人中心',
    'nav.logout': '退出',
    'nav.welcome': '欢迎',
    'nav.user': '用户',
    'nav.loading': '加载中...',
    'nav.honorific': '',
    'nav.back': '返回',
    
    // 히어로 섹션
    'hero.title': '中国体验团',
    'hero.subtitle': '在韩中国留学生的专属产品体验平台',
    'hero.description': '体验最新韩国产品，分享真实感受，获得丰厚奖励。加入我们，开启你的韩国产品体验之旅！',
    'hero.cta1': '立即体验',
    'hero.cta2': '了解更多',
    
    // 체험단 목록
    'experiences.title': '小洪书体验团',
    'experiences.subtitle': '精选韩国优质品牌体验机会，等你来参与',
    
    // 인스타 체험단
    'instagram.title': 'Instagram体验团',
    'instagram.subtitle': '精选韩国优质品牌Instagram体验机会，等你来参与',
    'instagram.description': '在Instagram上体验韩国产品，创作美丽内容，获得丰厚奖励。立即参与，开启你的Instagram网红之旅！',
    'experiences.filter.all': '全部',
    'experiences.filter.recruiting': '招募中',
    'experiences.filter.ongoing': '进行中',
    'experiences.filter.completed': '已完成',
    'experiences.more': '查看更多体验活动',
    
    // 체험단 카드
    'card.new': '新活动',
    'card.urgent': '紧急',
    'card.participants': '人',
    'card.daysLeft': '还剩',
    'card.days': '天',
    'card.full': '已满员',
    'card.apply': '立即报名',
    'card.imagePlaceholder': '产品图片',
    'card.experience': '体验团',
    'card.reporter': '记者团',
    'card.recruiting': '招募中',
    'card.ongoing': '进行中',
    'card.completed': '已完成',
    'card.closed': '已结束',
    'card.loading': '加载中...',
    
    // 로그인/회원가입
    'auth.login.title': '登录您的账户',
    'auth.login.noAccount': '还没有账户？',
    'auth.login.register': '立即注册',
    'auth.login.forgot': '忘记密码？',
    'auth.login.email': '邮箱地址',
    'auth.login.password': '密码',
    'auth.login.submit': '登录',
    'auth.login.loading': '登录中...',
    
    'auth.register.title': '创建新账户',
    'auth.register.hasAccount': '已有账户？',
    'auth.register.login': '立即登录',
    'auth.register.name': '姓名',
    'auth.register.phone': '手机号码',
    'auth.register.studentId': '学号',
    'auth.register.university': '大学',
    'auth.register.major': '专业',
    'auth.register.year': '年级',
    'auth.register.yearSelect': '请选择年级',
    'auth.register.year1': '1年级',
    'auth.register.year2': '2年级',
    'auth.register.year3': '3年级',
    'auth.register.year4': '4年级',
    'auth.register.year5': '5年级及以上',
    'auth.register.confirmPassword': '确认密码',
    'auth.register.submit': '注册',
    'auth.register.loading': '注册中...',
    'auth.register.passwordMismatch': '密码不匹配',
    'auth.register.passwordLength': '密码至少需要6个字符',
    
    // 프로필
    'profile.title': '个人中心',
    'profile.email': '邮箱',
    'profile.edit': '编辑信息',
    'profile.cancel': '取消',
    'profile.save': '保存',
    'profile.saving': '保存中...',
    'profile.success': '个人信息更新成功！',
    'profile.error': '更新失败，请重试',
    
    // 사이트 제목
    'site.title': '好卖的体验团',
    'site.description': '专为在韩中国留学生的产品体验平台，提供最新韩国品牌体验机会，分享真实感受，获得丰厚奖励。',
    
    // 푸터
    'footer.navigation': '快速导航',
    'footer.support': '客户支持',
    'footer.help': '帮助中心',
    'footer.contact': '联系我们',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.copyright': '© 2025 好卖的体验团. All rights reserved.',
    'footer.service': '专为在韩中国留学生服务',
    
    // 마이페이지
    'mypage.title': '个人中心',
    'mypage.profile': '个人资料',
    'mypage.stats': '申请统计',
    'mypage.totalApplications': '总申请',
    'mypage.approvedApplications': '已批准申请',
    'mypage.pendingApplications': '待处理申请',
    'mypage.rejectedApplications': '已拒绝申请',
    'mypage.applications': '申请记录',
    'mypage.applicationsDescription': '查看体验团申请状态',
    'mypage.loading': '正在加载申请记录...',
    'mypage.noApplications': '暂无申请记录',
    'mypage.noApplicationsDescription': '您还没有申请任何体验团。',
    'mypage.goHome': '返回首页',
    'mypage.appliedDate': '申请日期',
    'mypage.visitDate': '访问日期',
    'mypage.visitTime': '访问时间',
    'mypage.visitorCount': '访问人数',
    'mypage.status': '状态',
    'mypage.status.pending': '待处理',
    'mypage.status.approved': '已批准',
        'mypage.status.rejected': '已拒绝',
        'mypage.unknown': '未知',
        'mypage.undecided': '未定',
        'mypage.header': '页头',
        'mypage.goHomeButton': '返回首页按钮',
        'mypage.people': '人',
    
    // 상세페이지
    'detail.loading': '正在加载体验团信息...',
    'detail.notFound': '找不到体验团',
    'detail.images': '体验团图片',
    'detail.benefits': '体验团福利',
    'detail.requirements': '参与条件',
    'detail.application': '体验团申请',
    'detail.applying': '申请中...',
    'detail.applied': '申请完成',
    'detail.applyButton': '体验团申请',
    'detail.applicationCard': '体验团申请',
    'detail.infoCard': '体验团信息',
    'detail.ongoing': '进行中的体验团',
    'detail.completed': '已完成的体验团',
    'detail.name': '姓名',
    'detail.passportNumber': '护照号码',
    'detail.visitDate': '访问日期',
    'detail.visitTime': '访问时间',
    'detail.visitTimePeriod': '上午/下午',
    'detail.visitTimeHour': '小时',
    'detail.visitTimeMinute': '分钟',
    'detail.visitCount': '访问人数',
    'detail.wechatId': '微信ID',
    'detail.xiaohongshuId': '小红书ID',
    'detail.followerCount': '粉丝数',
    'detail.submit': '申请',
    'detail.location': '地点',
    'detail.date': '日期',
    'detail.time': '时间',
    'detail.participants': '参与者',
        'detail.contact': '联系',
        'detail.registrationDate': '注册日期',
        'detail.remainingDays': '剩余天数',
        'detail.category': '类别',
        'detail.status': '状态',
        'detail.imageError': '无法加载图片',
        'detail.noBenefits': '暂无福利信息',
        'detail.noRequirements': '暂无参与条件',
        'detail.unknown': '未知',
        'detail.header': '页头',
        'detail.mainContent': '主要内容',
        'detail.multipleImages': '多张图片',
        'detail.singleImage': '单张图片',
        'detail.image': '图片',
        'detail.titleAndInfo': '标题及基本信息',
        'detail.am': '上午',
        'detail.pm': '下午',
        'detail.hour': '时',
        'detail.minute': '分',
        'detail.people': '人',
        'detail.orMore': '以上',
        'detail.privacyConsent': '同意个人信息收集及使用',
        'detail.applicationForm': '体验团申请表单',
        'detail.sidebar': '侧边栏',
        'detail.noDateInfo': '无日期信息',
        'detail.day': '天',
        'detail.success': '成功',
        'detail.applicationInfo': '申请信息',
        'detail.daysLeft': '剩余天数',
        'detail.experienceApplication': '体验申请',
        'detail.instagramId': 'Instagram ID',
        'detail.pleaseEnterWechat': '请输入您的微信ID',
        'detail.pleaseEnterInstagram': '请输入您的Instagram ID',
        'detail.pleaseEnterFollowers': '请输入您的粉丝数量',
        'detail.applicationComplete': '申请完成',
        'detail.applyNow': '立即申请',
        'detail.loginRequired': '需要登录才能申请',
    'detail.phoneNumber': '电话号码',
    'detail.email': '邮箱',
    'detail.experienceDate': '体验日期',
    'detail.experienceTime': '体验时间',
    'detail.visitPurpose': '访问目的',
    'detail.previousExperience': '以往体验经历',
    'detail.socialMediaLinks': '社交媒体链接',
    'detail.additionalInfo': '附加信息',
    'detail.selectPeriod': '选择时段',
    'detail.selectHour': '选择小时',
    'detail.selectMinute': '选择分钟',
    'detail.selectCount': '选择人数',
    'detail.recruiting': '招募中',
    'detail.tags': '标签',
    
    // 관리자
    'admin.users': '사용자 관리',
    'admin.usersDesc': '등록된 사용자 정보 관리',
    'admin.experiences': '체험단 관리',
    'admin.experiencesDesc': '체험단 활동 관리',
    'admin.statistics': '데이터 통계',
    'admin.statisticsDesc': '웹사이트 사용 통계 확인',
    'admin.manage': '관리',
    'admin.view': '보기'
  },
  ko: {
    // 헤더
    'nav.home': '샤오홍슈',
    'nav.instagram': '인스타',
    'nav.experiences': '체험단',
    'nav.reviews': '후기',
    'nav.about': '소개',
    'nav.admin': '관리자',
    'nav.login': '로그인',
    'nav.register': '회원가입',
    'nav.mypage': '마이페이지',
    'nav.logout': '로그아웃',
    'nav.welcome': '환영합니다',
    'nav.user': '사용자',
    'nav.loading': '로딩중...',
    'nav.honorific': '님',
    'nav.back': '뒤로가기',
    
    // 히어로 섹션
    'hero.title': '중국 체험단',
    'hero.subtitle': '한국 내 중국 유학생을 위한 전용 제품 체험 플랫폼',
    'hero.description': '최신 한국 제품을 체험하고, 진짜 후기를 공유하며, 풍성한 보상을 받으세요. 지금 참여하여 한국 제품 체험의 여정을 시작하세요!',
    'hero.cta1': '지금 체험하기',
    'hero.cta2': '더 알아보기',
    
    // 체험단 목록
    'experiences.title': '샤오홍슈 체험단',
    'experiences.subtitle': '엄선된 한국 우수 브랜드 체험 기회를 놓치지 마세요',
    
    // 인스타 체험단
    'instagram.title': '인스타 체험단',
    'instagram.subtitle': '엄선된 한국 우수 브랜드 인스타그램 체험 기회를 놓치지 마세요',
    'instagram.description': '인스타그램에서 한국 제품을 체험하고, 아름다운 콘텐츠를 제작하며, 풍성한 보상을 받으세요. 지금 참여하여 인스타그램 인플루언서의 여정을 시작하세요!',
    'experiences.filter.all': '전체',
    'experiences.filter.recruiting': '모집중',
    'experiences.filter.ongoing': '진행중',
    'experiences.filter.completed': '완료',
    'experiences.more': '더 많은 체험단 보기',
    
    // 체험단 카드
    'card.new': '신규',
    'card.urgent': '긴급',
    'card.participants': '명',
    'card.daysLeft': '남은 기간',
    'card.days': '일',
    'card.full': '마감',
    'card.apply': '지금신청',
    'card.imagePlaceholder': '제품 이미지',
    'card.experience': '체험단',
    'card.reporter': '기자단',
    'card.recruiting': '모집중',
    'card.ongoing': '진행중',
    'card.completed': '완료',
    'card.closed': '마감',
    'card.loading': '로딩중...',
    
    // 로그인/회원가입
    'auth.login.title': '계정에 로그인',
    'auth.login.noAccount': '계정이 없으신가요?',
    'auth.login.register': '지금 가입하기',
    'auth.login.forgot': '비밀번호를 잊으셨나요?',
    'auth.login.email': '이메일 주소',
    'auth.login.password': '비밀번호',
    'auth.login.submit': '로그인',
    'auth.login.loading': '로그인 중...',
    
    'auth.register.title': '새 계정 만들기',
    'auth.register.hasAccount': '이미 계정이 있으신가요?',
    'auth.register.login': '지금 로그인',
    'auth.register.name': '이름',
    'auth.register.phone': '휴대폰 번호',
    'auth.register.studentId': '학번',
    'auth.register.university': '대학교',
    'auth.register.major': '전공',
    'auth.register.year': '학년',
    'auth.register.yearSelect': '학년을 선택하세요',
    'auth.register.year1': '1학년',
    'auth.register.year2': '2학년',
    'auth.register.year3': '3학년',
    'auth.register.year4': '4학년',
    'auth.register.year5': '5학년 이상',
    'auth.register.confirmPassword': '비밀번호 확인',
    'auth.register.submit': '가입',
    'auth.register.loading': '가입 중...',
    'auth.register.passwordMismatch': '비밀번호가 일치하지 않습니다',
    'auth.register.passwordLength': '비밀번호는 최소 6자 이상이어야 합니다',
    
    // 프로필
    'profile.title': '마이페이지',
    'profile.email': '이메일',
    'profile.edit': '정보 수정',
    'profile.cancel': '취소',
    'profile.save': '저장',
    'profile.saving': '저장 중...',
    'profile.success': '개인정보가 성공적으로 업데이트되었습니다!',
    'profile.error': '업데이트에 실패했습니다. 다시 시도해주세요.',
    
    // 사이트 제목
    'site.title': '잘파는 체험단',
    'site.description': '한국에서 중국인을 위한 제품 체험 플랫폼, 최신 한국 브랜드 체험 기회 제공, 진짜 후기 공유하고 풍성한 보상 받기.',
    
    // 푸터
    'footer.navigation': '빠른 링크',
    'footer.support': '고객 지원',
    'footer.help': '도움말',
    'footer.contact': '문의하기',
    'footer.privacy': '개인정보처리방침',
    'footer.terms': '서비스 약관',
    'footer.copyright': '© 2025 잘파는 체험단. All rights reserved.',
    'footer.service': '한국 내 중국 유학생을 위해 서비스',
    
    // 마이페이지
    'mypage.title': '마이페이지',
    'mypage.profile': '프로필',
    'mypage.stats': '신청 통계',
    'mypage.totalApplications': '총 신청',
    'mypage.approvedApplications': '승인된 신청',
    'mypage.pendingApplications': '대기 중인 신청',
    'mypage.rejectedApplications': '거부된 신청',
    'mypage.applications': '신청 내역',
    'mypage.applicationsDescription': '체험단 신청 현황을 확인하세요',
    'mypage.loading': '신청 내역을 불러오는 중...',
    'mypage.noApplications': '신청 내역이 없습니다',
    'mypage.noApplicationsDescription': '아직 신청한 체험단이 없습니다.',
    'mypage.goHome': '홈으로 돌아가기',
    'mypage.appliedDate': '신청일',
    'mypage.visitDate': '방문일',
    'mypage.visitTime': '방문시간',
    'mypage.visitorCount': '방문인원',
    'mypage.status': '상태',
    'mypage.status.pending': '대기중',
    'mypage.status.approved': '승인됨',
        'mypage.status.rejected': '거부됨',
        'mypage.unknown': '알 수 없음',
        'mypage.undecided': '미정',
        'mypage.header': '헤더',
        'mypage.goHomeButton': '홈으로 돌아가기 버튼',
        'mypage.people': '명',
    
    // 상세페이지
    'detail.loading': '체험단 정보를 불러오는 중...',
    'detail.notFound': '체험단을 찾을 수 없습니다',
    'detail.images': '체험단 이미지',
    'detail.benefits': '체험단 혜택',
    'detail.requirements': '참여 조건',
    'detail.application': '체험단 신청하기',
    'detail.applying': '신청 중...',
    'detail.applied': '신청 완료',
    'detail.applyButton': '체험단 신청하기',
    'detail.applicationCard': '체험단 신청',
    'detail.infoCard': '체험단 정보',
    'detail.ongoing': '진행 중인 체험단',
    'detail.completed': '완료된 체험단',
    'detail.name': '이름',
    'detail.passportNumber': '여권번호',
    'detail.visitDate': '방문날짜',
    'detail.visitTime': '방문시간',
    'detail.visitTimePeriod': '오전/오후',
    'detail.visitTimeHour': '시간',
    'detail.visitTimeMinute': '분',
    'detail.visitCount': '방문인원',
    'detail.wechatId': '위쳇 아이디',
    'detail.xiaohongshuId': '샤오홍슈 아이디',
    'detail.followerCount': '팔로워 수',
    'detail.submit': '신청하기',
    'detail.location': '장소',
    'detail.date': '날짜',
    'detail.time': '시간',
    'detail.participants': '참여자',
        'detail.contact': '문의',
        'detail.registrationDate': '등록일',
        'detail.remainingDays': '남은 기간',
        'detail.category': '카테고리',
        'detail.status': '상태',
        'detail.imageError': '이미지를 불러올 수 없습니다',
        'detail.noBenefits': '혜택 정보가 없습니다',
        'detail.noRequirements': '참여 조건이 없습니다',
        'detail.unknown': '알 수 없음',
        'detail.header': '헤더',
        'detail.mainContent': '메인 콘텐츠',
        'detail.multipleImages': '여러 이미지',
        'detail.singleImage': '단일 이미지',
        'detail.image': '이미지',
        'detail.titleAndInfo': '제목 및 기본 정보',
        'detail.am': '오전',
        'detail.pm': '오후',
        'detail.hour': '시',
        'detail.minute': '분',
        'detail.people': '명',
        'detail.orMore': '이상',
        'detail.privacyConsent': '개인정보 수집 및 이용에 동의합니다',
        'detail.applicationForm': '체험단 신청 폼',
        'detail.sidebar': '사이드바',
        'detail.noDateInfo': '날짜 정보 없음',
        'detail.day': '일',
        'detail.success': '성공',
        'detail.applicationInfo': '신청 정보',
        'detail.daysLeft': '남은 일수',
        'detail.experienceApplication': '체험단 신청',
        'detail.instagramId': '인스타그램 아이디',
        'detail.pleaseEnterWechat': '위쳇 아이디를 입력해주세요',
        'detail.pleaseEnterInstagram': '인스타그램 아이디를 입력해주세요',
        'detail.pleaseEnterFollowers': '팔로워 수를 입력해주세요',
        'detail.applicationComplete': '신청 완료',
        'detail.applyNow': '지금 신청하기',
        'detail.loginRequired': '신청하려면 로그인이 필요합니다',
        'detail.phoneNumber': '전화번호',
        'detail.email': '이메일',
        'detail.experienceDate': '체험 날짜',
        'detail.experienceTime': '체험 시간',
        'detail.visitPurpose': '방문 목적',
        'detail.previousExperience': '이전 체험 경험',
        'detail.socialMediaLinks': '소셜미디어 링크',
        'detail.additionalInfo': '추가 정보',
        'detail.selectPeriod': '선택',
        'detail.selectHour': '시간',
        'detail.selectMinute': '분',
        'detail.selectCount': '인원 선택',
        'detail.recruiting': '모집중',
        'detail.tags': '태그'
  },
  en: {
    // 헤더
    'nav.home': 'Xiaohongshu',
    'nav.instagram': 'Instagram',
    'nav.experiences': 'Experiences',
    'nav.reviews': 'Reviews',
    'nav.about': 'About',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.mypage': 'My Page',
    'nav.logout': 'Logout',
    'nav.welcome': 'Welcome',
    'nav.user': 'User',
    'nav.loading': 'Loading...',
    'nav.honorific': '',
    'nav.back': 'Back',
    
    // 히어로 섹션
    'hero.title': 'Chinese Experience Groups',
    'hero.subtitle': 'Exclusive product experience platform for Chinese students in Korea',
    'hero.description': 'Experience the latest Korean products, share authentic reviews, and receive generous rewards. Join us and start your Korean product experience journey!',
    'hero.cta1': 'Experience Now',
    'hero.cta2': 'Learn More',
    
    // 체험단 목록
    'experiences.title': 'Xiaohongshu Experience Groups',
    'experiences.subtitle': 'Don\'t miss out on carefully selected Korean premium brand experience opportunities',
    
    // 인스타 체험단
    'instagram.title': 'Instagram Experience Groups',
    'instagram.subtitle': 'Don\'t miss out on carefully selected Korean premium brand Instagram experience opportunities',
    'instagram.description': 'Experience Korean products on Instagram, create beautiful content, and receive generous rewards. Join now and start your Instagram influencer journey!',
    'experiences.filter.all': 'All',
    'experiences.filter.recruiting': 'Recruiting',
    'experiences.filter.ongoing': 'Ongoing',
    'experiences.filter.completed': 'Completed',
    'experiences.more': 'View More Experiences',
    
    // 체험단 카드
    'card.new': 'New',
    'card.urgent': 'Urgent',
    'card.participants': 'people',
    'card.daysLeft': 'days left',
    'card.days': 'days',
    'card.full': 'Full',
    'card.apply': 'Apply Now',
    'card.imagePlaceholder': 'Product Image',
    'card.experience': 'Experience',
    'card.reporter': 'Reporter',
    'card.recruiting': 'Recruiting',
    'card.ongoing': 'Ongoing',
    'card.completed': 'Completed',
    'card.closed': 'Closed',
    'card.loading': 'Loading...',
    
    // 로그인/회원가입
    'auth.login.title': 'Login to Your Account',
    'auth.login.noAccount': 'Don\'t have an account?',
    'auth.login.register': 'Register Now',
    'auth.login.forgot': 'Forgot Password?',
    'auth.login.email': 'Email Address',
    'auth.login.password': 'Password',
    'auth.login.submit': 'Login',
    'auth.login.loading': 'Logging in...',
    
    'auth.register.title': 'Create New Account',
    'auth.register.hasAccount': 'Already have an account?',
    'auth.register.login': 'Login Now',
    'auth.register.name': 'Name',
    'auth.register.phone': 'Phone Number',
    'auth.register.studentId': 'Student ID',
    'auth.register.university': 'University',
    'auth.register.major': 'Major',
    'auth.register.year': 'Year',
    'auth.register.yearSelect': 'Please select year',
    'auth.register.year1': '1st Year',
    'auth.register.year2': '2nd Year',
    'auth.register.year3': '3rd Year',
    'auth.register.year4': '4th Year',
    'auth.register.year5': '5th Year and above',
    'auth.register.confirmPassword': 'Confirm Password',
    'auth.register.submit': 'Register',
    'auth.register.loading': 'Registering...',
    'auth.register.passwordMismatch': 'Passwords do not match',
    'auth.register.passwordLength': 'Password must be at least 6 characters',
    
    // 프로필
    'profile.title': 'My Page',
    'profile.email': 'Email',
    'profile.edit': 'Edit Info',
    'profile.cancel': 'Cancel',
    'profile.save': 'Save',
    'profile.saving': 'Saving...',
    'profile.success': 'Profile updated successfully!',
    'profile.error': 'Update failed, please try again',
    
    // 사이트 제목
    'site.title': 'Popular Experience Groups',
    'site.description': 'Product experience platform for Chinese students in Korea, providing latest Korean brand experience opportunities, sharing authentic reviews and receiving generous rewards.',
    
    // 푸터
    'footer.navigation': 'Quick Links',
    'footer.support': 'Customer Support',
    'footer.help': 'Help Center',
    'footer.contact': 'Contact Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2025 Popular Experience Groups. All rights reserved.',
    'footer.service': 'Serving Chinese students in Korea',
    
    // 마이페이지
    'mypage.title': 'My Page',
    'mypage.profile': 'Profile',
    'mypage.stats': 'Application Statistics',
    'mypage.totalApplications': 'Total Applications',
    'mypage.approvedApplications': 'Approved Applications',
    'mypage.pendingApplications': 'Pending Applications',
    'mypage.rejectedApplications': 'Rejected Applications',
    'mypage.applications': 'Application History',
    'mypage.applicationsDescription': 'Check your experience group application status',
    'mypage.loading': 'Loading application history...',
    'mypage.noApplications': 'No application history',
    'mypage.noApplicationsDescription': 'You haven\'t applied to any experience groups yet.',
    'mypage.goHome': 'Go Home',
    'mypage.appliedDate': 'Applied Date',
    'mypage.visitDate': 'Visit Date',
    'mypage.visitTime': 'Visit Time',
    'mypage.visitorCount': 'Visitor Count',
    'mypage.status': 'Status',
    'mypage.status.pending': 'Pending',
    'mypage.status.approved': 'Approved',
    'mypage.status.rejected': 'Rejected',
    'mypage.unknown': 'Unknown',
    'mypage.undecided': 'Undecided',
    'mypage.header': 'Header',
    'mypage.goHomeButton': 'Go Home Button',
    'mypage.people': 'people',
    
    // 상세페이지
    'detail.loading': 'Loading experience group information...',
    'detail.notFound': 'Experience group not found',
    'detail.images': 'Experience Group Images',
    'detail.benefits': 'Experience Group Benefits',
    'detail.requirements': 'Participation Requirements',
    'detail.application': 'Experience Group Application',
    'detail.applying': 'Applying...',
    'detail.applied': 'Application Complete',
    'detail.applyButton': 'Apply to Experience Group',
    'detail.applicationCard': 'Experience Group Application',
    'detail.infoCard': 'Experience Group Information',
    'detail.ongoing': 'Ongoing Experience Groups',
    'detail.completed': 'Completed Experience Groups',
    'detail.name': 'Name',
    'detail.passportNumber': 'Passport Number',
    'detail.visitDate': 'Visit Date',
    'detail.visitTime': 'Visit Time',
    'detail.visitTimePeriod': 'AM/PM',
    'detail.visitTimeHour': 'Hour',
    'detail.visitTimeMinute': 'Minute',
    'detail.visitCount': 'Visitor Count',
    'detail.wechatId': 'WeChat ID',
    'detail.xiaohongshuId': 'Xiaohongshu ID',
    'detail.followerCount': 'Follower Count',
    'detail.submit': 'Apply',
    'detail.location': 'Location',
    'detail.date': 'Date',
    'detail.time': 'Time',
    'detail.participants': 'Participants',
    'detail.contact': 'Contact',
    'detail.registrationDate': 'Registration Date',
    'detail.remainingDays': 'Remaining Days',
    'detail.category': 'Category',
    'detail.status': 'Status',
    'detail.imageError': 'Unable to load image',
    'detail.noBenefits': 'No benefit information available',
    'detail.noRequirements': 'No participation requirements',
    'detail.unknown': 'Unknown',
    'detail.header': 'Header',
    'detail.mainContent': 'Main Content',
    'detail.multipleImages': 'Multiple Images',
    'detail.singleImage': 'Single Image',
    'detail.image': 'Image',
    'detail.titleAndInfo': 'Title and Basic Information',
    'detail.am': 'AM',
    'detail.pm': 'PM',
    'detail.hour': 'Hour',
    'detail.minute': 'Min',
    'detail.people': 'people',
    'detail.orMore': 'or more',
    'detail.privacyConsent': 'I agree to the collection and use of personal information',
    'detail.applicationForm': 'Experience Group Application Form',
    'detail.sidebar': 'Sidebar',
    'detail.noDateInfo': 'No date information',
    'detail.day': 'day',
    'detail.success': 'Success',
    'detail.applicationInfo': 'Application Info',
    'detail.daysLeft': 'Days Left',
    'detail.experienceApplication': 'Experience Application',
    'detail.instagramId': 'Instagram ID',
    'detail.pleaseEnterWechat': 'Please enter your WeChat ID',
    'detail.pleaseEnterInstagram': 'Please enter your Instagram ID',
    'detail.pleaseEnterFollowers': 'Please enter your follower count',
    'detail.applicationComplete': 'Application Complete',
    'detail.applyNow': 'Apply Now',
    'detail.loginRequired': 'Login required to apply',
    'detail.phoneNumber': 'Phone Number',
    'detail.email': 'Email',
    'detail.experienceDate': 'Experience Date',
    'detail.experienceTime': 'Experience Time',
    'detail.visitPurpose': 'Visit Purpose',
    'detail.previousExperience': 'Previous Experience',
    'detail.socialMediaLinks': 'Social Media Links',
    'detail.additionalInfo': 'Additional Information',
    'detail.selectPeriod': 'Select Period',
    'detail.selectHour': 'Select Hour',
    'detail.selectMinute': 'Select Minute',
    'detail.selectCount': 'Select Count',
    'detail.recruiting': 'Recruiting',
    'detail.tags': 'Tags',
    
    // 관리자
    'admin.users': 'User Management',
    'admin.usersDesc': 'Manage registered user information',
    'admin.experiences': 'Experience Management',
    'admin.experiencesDesc': 'Manage experience group activities',
    'admin.statistics': 'Data Statistics',
    'admin.statisticsDesc': 'Check website usage statistics',
    'admin.manage': 'Manage',
    'admin.view': 'View'
  }
}

interface LanguageProviderProps {
  children: ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('ko')

  // 로컬 스토리지에서 언어 설정 불러오기
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'zh' || savedLanguage === 'ko' || savedLanguage === 'en')) {
      setLanguage(savedLanguage)
      // HTML lang 속성 설정
      if (typeof document !== 'undefined') {
        document.documentElement.lang = savedLanguage === 'zh' ? 'zh-CN' : 
                                       savedLanguage === 'ko' ? 'ko-KR' : 'en-US'
      }
    }
  }, [])

  // 언어 변경 시 로컬 스토리지에 저장
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
    
    // HTML lang 속성 동적 변경
    if (typeof document !== 'undefined') {
      document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 
                                     lang === 'ko' ? 'ko-KR' : 'en-US'
    }
  }

  // 번역 함수
  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]]
    return translation !== undefined ? translation : key
  }

  return (
    <LanguageContext.Provider value={{ language, currentLanguage: language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
